#!/usr/bin/env python3
"""Extract contacts from raw text and upload to Supabase."""
import re
import requests
import time
import json

SUPABASE_URL = "https://qwkwkemuabfwvwuqrxlu.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3a3drZW11YWJmd3Z3dXFyeGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1OTk5NjEsImV4cCI6MjA4NzE3NTk2MX0.JxEYiWVPEOiwjZtbWAZRlMUdKXcupjw7filvrERCiqc"

HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal"
}

# All contacts extracted from the data
CONTACTS = [
    {"nome": "Perrone Giada", "email": "giadaperrone2006@gmail.com"},
    {"nome": "Simionato Ilaria", "email": "ilariasimionato01@gmail.com", "codice_fiscale": "SMNLRI01P69B563A", "indirizzo_cliente": "Via Villanova 15C, 35010 Trebaseleghe (Padova)"},
    {"nome": "Pagnin Arianna", "email": "pagninarianna@gmail.com", "codice_fiscale": "PGNRNN88H42G224Y", "indirizzo_cliente": "Via Monte Cengio 7B, 35010 Curtarolo (Padova)"},
    {"nome": "Chianca Valerio", "email": "avv.chianca@libero.it"},
    {"nome": "Milan Donatella", "email": "josellamilan@gmail.com", "codice_fiscale": "MLNSLL59A70G587B", "indirizzo_cliente": "Via Don Luigi Sturzo 12, 35010 Vigodarzere (Padova)"},
    {"nome": "Saccardo Sandro", "email": "nbpadova@gmail.com", "codice_fiscale": "SCCSDR77E01B563R", "indirizzo_cliente": "Via Mazzini 2, 35010 Limena (Padova)"},
    {"nome": "Casanova Gabriella", "email": "gabriellacasanova73@gmail.com"},
    {"nome": "La Soluzione Che Cerchi Srl", "email": "ferrari@humanoption.it", "ragione_sociale": "La Soluzione Che Cerchi Srl", "tipo_cliente": "azienda"},
    {"nome": "Gambali Anna", "email": "anna.gambali@silaq.it"},
    {"nome": "Bano Nicola", "email": "nbpadova@gmail.com", "codice_fiscale": "BNANCL85E25G224J", "indirizzo_cliente": "P.zza Diaz 44, 35010 Limena (Padova)"},
    {"nome": "Adamo Rosa Maria", "email": "corso.mariacristina7@libero.it", "codice_fiscale": "DMARMR48L58L331I"},
    {"nome": "Zanarello Greta", "email": "gretazanarello.gz@gmail.com"},
    {"nome": "Lindamarket Leo", "email": "lindamarket91@gmail.com"},
    {"nome": "Favaretto Stefania", "email": "stefania.favaretto.3@gmail.com"},
    {"nome": "Ressi Sergio", "email": "sergioressi@gmail.com"},
    {"nome": "Zaramella Laura", "email": "laurazaramella3@gmail.com"},
    {"nome": "Zangaro Vittoria", "email": "vittoria.zangaro@gmail.com"},
    {"nome": "Stefu Mihaela", "email": "mihaelastefu8@gmail.com"},
    {"nome": "Maragno Alessio", "email": "alessio.maragno85@gmail.com"},
    {"nome": "Serghei Grosu", "email": "sere2008zzz@gmail.com"},
    {"nome": "Grigolon Ivan", "email": "grigolon.ivan@gmail.com"},
    {"nome": "Martini Fabio", "email": "fabio.martini@martiniopere.it"},
    {"nome": "Sanguin Francesca", "email": "f.sanguin@tiscali.it"},
    {"nome": "Braghis Nina", "email": "nina.braghis@outlook.it"},
    {"nome": "Vegro Anna", "email": "annavegro77@gmail.com"},
    {"nome": "Tenan Chiara", "email": "chiaratenan79@gmail.com"},
    {"nome": "Balazhi Safet", "email": "safetbalazi69@gmail.com"},
    {"nome": "Vivian", "email": "nazorowa@yahoo.com"},
    {"nome": "Obilonu Anne", "email": "beauty.akore@libero.it"},
    {"nome": "Trocin Elisaveta", "email": "elisaveta.trocin@gmail.com"},
    {"nome": "Alexandra Esanu", "email": "alexandraesanu37@gmail.com"},
    {"nome": "Barasti Carlo", "email": "carlo.barasti@gmail.com"},
    {"nome": "Ferro Giorgia", "email": "giorgiagiuliaferro@hotmail.it", "codice_fiscale": "FRRGRG96B68G224C", "indirizzo_cliente": "Via Gioberti 10, 35030 Rubano (Padova)"},
    {"nome": "Olesea", "email": "tcaciolesea93@gmail.com"},
    {"nome": "Mortaruolo Domenico", "email": "mimmomortaruolo@live.it", "codice_fiscale": "MRTDNC94H25A783H", "indirizzo_cliente": "Via Ospedale 2, Benevento"},
    {"nome": "Celacu Marina", "email": "marina.celacu71@gmail.com"},
    {"nome": "Salvato Michele", "email": "michele.salvato.pd@gmail.com"},
    {"nome": "Cardone Tatiana", "email": "tati152006@hotmail.com"},
    {"nome": "Bellantone Giulia", "email": "bellantonegiulia@hotmail.it"},
    {"nome": "Cardin Silvia", "email": "silviacardin40@gmail.com"},
    {"nome": "Romeo Tamara", "email": "tamararomeo@gmail.com"},
    {"nome": "Patel Paresha", "email": "pate.paresha1987@gmail.com"},
    {"nome": "Bilato Lorenza", "email": "lorenza.bilato@gmail.com"},
    {"nome": "Rambaldi Laura", "email": "rambaldi.laura@gmail.com"},
    {"nome": "Andrea", "email": "andr.ross@hotmail.com"},
    {"nome": "Antonello Francesco", "email": "francesco.antonello33@gmail.com"},
    {"nome": "Callegaro Silvio", "email": "silvio.callegaro@live.it"},
    {"nome": "Moussa Ndiaye", "email": "ndiayemoussa7890@gmail.com"},
    {"nome": "Luci Arianna", "email": "ari7l94@gmail.com"},
    {"nome": "Bregante Sarah", "email": "sarahbregante@gmail.com"},
    {"nome": "Madalina Ariciu", "email": "madalinaperianu7@gmail.com"},
    {"nome": "Bergamini Barbara", "email": "barbara.bergamini@colorificiobz.net"},
    {"nome": "De Angeli Nicola", "email": "geom.deangeli@gmail.com"},
    {"nome": "Tafuro Michele", "email": "michele91tafuro@gmail.com"},
    {"nome": "Sarker Kamal", "email": "sarkerkamal75@gmail.com"},
    {"nome": "Aristo Laura", "email": "lauraaristo@libero.it"},
    {"nome": "Giusy", "email": "giusyfele98@gmail.com"},
    {"nome": "Izabela", "email": "izabelabici@gmail.com"},
    {"nome": "Peruzzo Maicol", "email": "maicol95peruzzo@gmail.com"},
    {"nome": "Arame", "email": "aramelo365@gmail.com"},
    {"nome": "Gianluca", "email": "gianluca.masenello@gmail.com"},
    {"nome": "Armillotta Teresa", "email": "armilteresa@gmail.com"},
    {"nome": "Vettore Martina", "email": "martyvetlm@gmail.com"},
    {"nome": "Russo Eleonora", "email": "ele.russo98@virgilio.it"},
    {"nome": "Scuderi Marco", "email": "scuderim94@gmail.com"},
    {"nome": "Zoccarato Chiara", "email": "chiarazoccarato76@gmail.com", "codice_fiscale": "ZCCCHR76P48G224H"},
    {"nome": "Righetto Monica", "email": "icoghetti@gmail.com", "codice_fiscale": "RGHMNC79C50B563Z"},
    {"nome": "Rippa Lorenzo", "email": "lorenzorippa@gmail.com", "codice_fiscale": "RPPLNZ99R06F839B"},
    {"nome": "Moscardi Federico", "email": "fedemosca0508@gmail.com"},
    {"nome": "Dante Nicola", "email": "nicola.dantex@gmail.com", "codice_fiscale": "DNTNCL79R16G224F"},
    {"nome": "Velo Cristina", "email": "cristinavelo54@gmail.com", "codice_fiscale": "VLECST65T47D679I"},
    {"nome": "Ghedin Giorgio Massimiliano", "email": "ghedin.marco1@gmail.com", "codice_fiscale": "GHDMSM40E15D442O"},
    {"nome": "Guasti Fabiola", "email": "fabiola.guasti72@gmail.com", "codice_fiscale": "GSTFBL72P66G693N"},
    {"nome": "Bano Franco", "email": "francobano57@gmail.com", "codice_fiscale": "BNAFNC57L01E592S"},
    {"nome": "Mazzaracca Andrea", "email": "andrea.mazzaracca@gmail.com", "codice_fiscale": "MZZNDR97S19C743N"},
    {"nome": "Costa Luca", "email": "luca.costa.1300@gmail.com", "codice_fiscale": "CSTLCU00T13G224O"},
    {"nome": "Fenu Lucia", "email": "lucia.fenu95@gmail.com", "codice_fiscale": "FNELCU95H70B745B"},
    {"nome": "Nezzoni Donatella", "email": "dantebano@libero.it", "codice_fiscale": "NZZDTL55E54L892Z"},
    {"nome": "Romanato Ana Paula", "email": "anapaula.romanato@outlook.it", "codice_fiscale": "RMNNPL95E55Z602J"},
    {"nome": "Petranzan Ketti", "email": "ketti.petranzan@gmail.com", "codice_fiscale": "PTRKTT96C43B563N"},
    {"nome": "Segato Mattia", "email": "mattiasegato12@gmail.com"},
    {"nome": "Di Lonardo Ilaria", "email": "ilariadilo@gmail.com", "codice_fiscale": "DLNLRI86T48F104L"},
    {"nome": "E-ON Energia", "email": "debora.agostini@eon.com", "ragione_sociale": "E-ON Energia S.p.a.", "tipo_cliente": "azienda"},
    {"nome": "Avoli Alberto", "email": "vitamedica58@gmail.com"},
    {"nome": "Natus Medical - Sgarabottolo Simona", "email": "simona.sgarabottolo@natus.com", "ragione_sociale": "Natus Medical", "tipo_cliente": "azienda"},
    {"nome": "Pinton Pamela", "email": "pamelapinton85@gmail.com"},
    {"nome": "Rubini Camilla", "email": "camilla.rubini@outlook.it", "codice_fiscale": "RBNCLL96S47B563D"},
    {"nome": "Ravagnan Spa", "email": "d.sabbadin@ravagnan.com", "ragione_sociale": "Ravagnan Spa", "partita_iva": "00230620288", "tipo_cliente": "azienda"},
    {"nome": "Pilloni Alvise", "email": "alvise.pilloni@umana.it"},
    {"nome": "Canache Roberto", "email": "elcanache80@gmail.com"},
    {"nome": "Giordano Antonella", "email": "antonella.g.1996@live.it", "codice_fiscale": "GRDNNL96E49H224L"},
    {"nome": "Gobbo Alberto", "email": "alberto.gobbo96@gmail.com"},
    {"nome": "Geos Ambiente Srl", "email": "amministrazione@geosambiente.com", "ragione_sociale": "Geos Ambiente Srl", "tipo_cliente": "azienda"},
    {"nome": "Hu Valentina", "email": "canalalbertoedoardo@gmail.com"},
    {"nome": "Bano Dante", "email": "dantebano@libero.it", "codice_fiscale": "BNADNT51M13E592X"},
    {"nome": "Tognon Ambra", "email": "andreaambra9@gmail.com", "codice_fiscale": "TGNMBR83A68G224J"},
    {"nome": "Da Bartola Deianira", "email": "deianiradibartola@gmail.com", "codice_fiscale": "DBRDNR97H50A638O"},
    {"nome": "Marcolongo Gioia", "email": "gioia3008@gmail.com"},
    {"nome": "Dias Angela", "email": "adias5504@gmail.com"},
    {"nome": "Bernardi Marco", "email": "marcobernardi42@gmail.com"},
    {"nome": "Negrato Matteo", "email": "negrato.matteo@icloud.com"},
    {"nome": "Medico Lucia", "email": "luciamerico91@gmail.com"},
    {"nome": "Bortolami Alessandra", "email": "alessandra.bortolami@virgilio.it"},
    {"nome": "Chiara Lorenzato", "email": "arch.lorenzato@gmail.com"},
    {"nome": "Griggio Michele", "email": "michigrey@libero.it"},
    {"nome": "Anna", "email": "annayellow@proton.me"},
    {"nome": "Giglio Marco", "email": "marco.giglio@alleanza.it", "codice_fiscale": "GGLMRC73P02A662X"},
    {"nome": "Bianco Elisabetta", "email": "elisabettabianco4@gmail.com", "codice_fiscale": "BNCLBT74L44G224E"},
    {"nome": "Mitica Adrian Petrica", "email": "bellmondo.adryan@gmail.com", "codice_fiscale": "MTCDNP91H25Z129A"},
    {"nome": "Marchioro Barbara", "email": "barbara.marchioro@gmail.com", "codice_fiscale": "MRCBBR78C55G224Y"},
    {"nome": "Vincenti Marco", "email": "marco.vincenti79@gmail.com", "codice_fiscale": "VNCMRC79H19G224H"},
    {"nome": "Stecca Giorgia", "email": "giorgia.stecca@gmail.com"},
    {"nome": "Favaron Carla", "email": "carla.favaron@tiscali.it"},
    {"nome": "Hairagain Padova - Lodoli Riccardo", "email": "lodolirik@gmail.com", "ragione_sociale": "Hairagain Padova Srl", "tipo_cliente": "azienda"},
    {"nome": "Aubelaid Mina", "email": "aubelaidmina@gmail.com"},
    {"nome": "Rusu Michaela", "email": "padovavia2019@gmail.com"},
    {"nome": "Bison Giacomo", "email": "giacomo.bison@libero.it", "codice_fiscale": "BSNGCM76P22L781A"},
    {"nome": "Marcellan Adriano", "email": "adrimar2011@libero.it", "codice_fiscale": "MRCDRN58L08G224A"},
    {"nome": "Noventa Francesca", "email": "franoventa@gmail.com"},
    {"nome": "Pasquini Matteo", "email": "matteo.pasquini@me.com", "codice_fiscale": "PSQMTT99R08L781J"},
    {"nome": "Vitale Noemi", "email": "noemi.vitale1098@gmail.com", "codice_fiscale": "VTLNMO98R56G348P"},
    {"nome": "Tanasaciuc Anca Giorgiana", "email": "ancageorgianatanasaciuc@gmail.com"},
    {"nome": "Bejan Yesim Alexandra", "email": "alexa_98mateo@yahoo.com", "codice_fiscale": "BJNYML98C57Z129E"},
    {"nome": "Boughaz Giovanni", "email": "abdallah.boughaz.personale@gmail.com"},
    {"nome": "Sgrilli Taira", "email": "sgrilli.taiara@gmail.com", "codice_fiscale": "SGRTRA01T47Z602F"},
    {"nome": "Peruzzo Alessandro", "email": "pillonialvise@gmail.com"},
    {"nome": "Lusardi Monica", "email": "monicalusardi@tiscali.it"},
    {"nome": "Bendetti Marco", "email": "marcobenettidesign@gmail.com"},
    {"nome": "Laboratorio 9 Srl", "email": "laboratorio9@pec.it", "ragione_sociale": "Laboratorio 9 Srl", "tipo_cliente": "azienda"},
    {"nome": "Griggio Carmen", "email": "grgcmn63a47g224m@pec.it"},
    {"nome": "Verrecchia Carmine", "email": "carmineverrecchia@libero.it", "codice_fiscale": "VRRCMN46H18L725H"},
    {"nome": "Solution House Srl", "email": "amministrazionerinnovabili@solutiontechnology.eu", "ragione_sociale": "Solution House Srl", "tipo_cliente": "azienda"},
    {"nome": "Sarti Alessandro", "email": "amm.autofficinasartisrl@gmail.com"},
    {"nome": "Anton", "email": "bererece30@gmail.com"},
    {"nome": "Sibe Sas - Bertocco", "email": "nicola@nnte.it", "ragione_sociale": "Sibe Sas di Bertocco Gianfranco & Figli", "tipo_cliente": "azienda"},
    {"nome": "Giacon Massimo", "email": "giaconimpianti@gmail.com", "codice_fiscale": "GCNMSM72C01G224P"},
    {"nome": "Contu Eros", "email": "cantueros@gmail.com"},
    {"nome": "Vergari Leonardo", "email": "vergari.leonardo@gmail.com"},
    {"nome": "Pau Valentino", "email": "valentino.pau@gmail.com"},
    {"nome": "Marangon Livio", "email": "maranga857@gmail.com", "codice_fiscale": "MRNLVI59T02L892N"},
    {"nome": "Paolo Aggujaro", "email": "pglgni37m11g224y@pec.it", "codice_fiscale": "GGJPLA51A09E592Y"},
    {"nome": "Martin Lara", "email": "00laramartin00@gmail.com"},
    {"nome": "Emilia Maria", "email": "mepolegato77@gmail.com"},
    {"nome": "Darfa Federico", "email": "federicodarfa@gmail.com", "codice_fiscale": "DRFFRC74R02G224E"},
    {"nome": "Corso Nicolò", "email": "corso.mariacristina7@libero.it", "codice_fiscale": "CRSNCL44M27F246M"},
    {"nome": "Zago Sabrina", "email": "nicoloealex@gmail.com"},
    {"nome": "Nardillo Donato", "email": "dnardillo@yahoo.it"},
    {"nome": "Galiazzo Paolo", "email": "paolo.galiazzo.1990@gmail.com"},
    {"nome": "Lucchetti Francesca", "email": "francescalucchetti1@hotmail.it"},
    {"nome": "Rizzi Matteo", "email": "matteorizzi4@gmail.com"},
    {"nome": "Castelli Ilaria", "email": "castelli.ilaria.96@gmail.com"},
    {"nome": "Boesso Laura", "email": "laura.boesso@gmail.com"},
    {"nome": "Sefosca Anisa", "email": "anisa.sefoska@gmail.com"},
    {"nome": "Caviness Marilena", "email": "marilenacickett3@gmail.com"},
    {"nome": "Simioni Riccardo", "email": "antonella96dangelo@gmail.com"},
    {"nome": "Pellegrino Sabrina", "email": "pellesabry@gmail.com"},
    {"nome": "Salerno Francesco", "email": "salefra4@gmail.com"},
    {"nome": "Congiu Niccolò", "email": "niccolocongiu94@gmail.com"},
    {"nome": "Corò Flavio", "email": "flaviocoro10@gmail.com"},
    {"nome": "Bianchi Riccardo", "email": "binachi.riccardo1988@gmail.com"},
    {"nome": "Zecchino Melissa", "email": "zecchino.melissa@gmail.com"},
    {"nome": "Panezzari Chiara", "email": "panezzari.chiara94@gmail.com"},
    {"nome": "Bianchi Sara", "email": "sarabianchi52347@gmail.com"},
    {"nome": "Pasquandrea Stefano", "email": "pasks86@gmail.com"},
    {"nome": "Tranquilli Angelica", "email": "angytranq@gmail.com"},
    {"nome": "Cardin Alessandro", "email": "cardin.alessandro@gmail.com", "codice_fiscale": "CRDLSN84S30G224W"},
    {"nome": "Hairagain Padova - Visentin Matteo", "email": "teovise83@gmail.com", "ragione_sociale": "Hairagain Padova Srl", "tipo_cliente": "azienda"},
    {"nome": "Cieri Emilia", "email": "emilia.cieri@yahoo.it"},
    {"nome": "Tengo Claudia", "email": "clatiengo1974@gmail.com"},
    {"nome": "Tombolato Carmen", "email": "carmen.tombolato@gmail.com"},
    {"nome": "Rares", "email": "mironrares5@gmail.com"},
    {"nome": "Biscosi Michele", "email": "blumic@live.it", "codice_fiscale": "BSCMHL73P30G224I"},
    {"nome": "Adami Laura", "email": "laura.adami1986@gmail.com"},
    {"nome": "Salmaso Marika", "email": "marikasalmaso96@gmail.com", "codice_fiscale": "SLMMRK96S65B563A"},
    {"nome": "Mariano Francesco", "email": "marianofrancesco8196@gmail.com", "codice_fiscale": "MRNFNC96A08F915N"},
    {"nome": "Dimare Serena", "email": "serenadimareph@gmail.com", "codice_fiscale": "DMRSRN96R66E977P"},
    {"nome": "Pentimalli Pierluigi", "email": "pierluigi.pentimalli@arengo.it"},
    {"nome": "Miang Abdou", "email": "abdoumiang2016@gmail.com"},
    {"nome": "Allegro Anita", "email": "anitaalle0603@gmail.com"},
    {"nome": "Lorenzato Lucio", "email": "lorenzatolucio@gmail.com", "codice_fiscale": "LRNLCU43D27D226K"},
    {"nome": "Becegato Giulio", "email": "hello@giuliobeccegato.it"},
    {"nome": "Disarò Claudio", "email": "dario.d2807@gmail.com"},
    {"nome": "Zaramella Renato", "email": "pazk1971@gmail.com", "codice_fiscale": "ZRMRNT71C03C743S"},
    {"nome": "Katia", "email": "m.kata@tiscali.it"},
    {"nome": "A.G. Srls", "email": "rediego76@gmail.com", "ragione_sociale": "A.G. Srls", "tipo_cliente": "azienda"},
    {"nome": "Turcanu Cornel Marian", "email": "cornel.turcanu@yahoo.it", "codice_fiscale": "TRCCNL87H28Z129Z"},
    {"nome": "Fabiana", "email": "fabiomobono80@gmail.com"},
    {"nome": "Volodymr", "email": "volodymr401@gmail.com"},
    {"nome": "Rai Prahlad", "email": "prahladrai730@gmail.com"},
    {"nome": "Pavan Desirè", "email": "desire.pavan96@gmail.com"},
    {"nome": "Andrea", "email": "adr31048@gmail.com"},
    {"nome": "Paolucci Isabella", "email": "paolisa9676@gmail.com"},
    {"nome": "Vildera Giovanni", "email": "giovildo@hotmail.it"},
    {"nome": "Rizzi Stefania", "email": "stefyrizzi@yahoo.it"},
    {"nome": "Angela Orlando", "email": "orlando.14angela@gmail.com"},
    {"nome": "Maso Ambra", "email": "ambra.maso@gmail.com"},
    {"nome": "Ruggiero Vincenza Silvana", "email": "ronnyechicca@yahoo.it"},
    {"nome": "De Agostini Cristina", "email": "c.deagostini@yahoo.it"},
    {"nome": "Ferialdi Marco", "email": "marcoferialdi255@gmail.com"},
    {"nome": "Montanaro Giuseppe", "email": "montanaropeppe@libero.it"},
    {"nome": "Anastasia", "email": "anasbarile@gmail.com"},
    {"nome": "Dengo Jessica", "email": "jessica.dengo90@gmail.com"},
    {"nome": "Collauzzo Laura", "email": "collauzzo.laura@gmail.com"},
    {"nome": "Tafuti Antonio", "email": "tonytafuti82@gmail.com"},
    {"nome": "Ferrandi Marco", "email": "marcodoctorglasspadova@gmail.com"},
    {"nome": "Boi Gabriella", "email": "gabriboi76@gmail.com"},
    {"nome": "Ciuchi Mirela", "email": "ciuchimirela87@gmail.com"},
    {"nome": "Zingaro Cristian", "email": "simonagramazio0208@gmail.com"},
    {"nome": "Boaretto Emanuela", "email": "emyboar@gmail.com"},
    {"nome": "Speranti Nicola", "email": "fabiomobono80@gmail.com"},
    {"nome": "Iannuzzi Sara", "email": "siannuzzi98@gmail.com"},
    {"nome": "Caldararu Andrei", "email": "caldararuo@gmail.com"},
    {"nome": "Pin Pietro", "email": "pietro.pin@hotmail.it"},
    {"nome": "Di Paolo Biagio", "email": "biagio.dipaolo95@gmail.com"},
    {"nome": "Perli Andrea", "email": "andrea.perli1976@gmail.com"},
    {"nome": "Murati Marjus", "email": "marjus.murati@gmail.com"},
    {"nome": "Quaggia Daniele", "email": "daniele@quaggia.it"},
    {"nome": "Furlan Elisabetta", "email": "efurlansch@gmail.com"},
    {"nome": "Serri Maria Chiara", "email": "chiara.serri@gmail.com"},
    {"nome": "Emanuela", "email": "manu_dunk@msn.com"},
    {"nome": "Mazzarolo Marco", "email": "marcomazzarolo85@gmail.com", "codice_fiscale": "MZZMRC85S04B563E"},
    {"nome": "Degli Agostini Mirella", "email": "mirbe.da@gmail.com"},
    {"nome": "Bilotti Chiara", "email": "chiarabilotti08@gmail.com"},
    {"nome": "Vattore Claudio", "email": "claudio.vettore@gmail.com"},
    {"nome": "Cibotto Federica", "email": "cibotto.federica@gmail.com"},
    {"nome": "Caschini Maria", "email": "maria.caschini0@gmail.com", "codice_fiscale": "CSCMRA65S59L049N"},
    {"nome": "Gabellone Irene", "email": "irene.gabellone.ig@gmail.com"},
    {"nome": "Valente Riccardo", "email": "richi22n@gmail.com"},
    {"nome": "Vettorato Nicola", "email": "info@counselorservice.it"},
    {"nome": "Rizzo F", "email": "f.rizzo@voltenergyitalia.it"},
    {"nome": "Felletti Donatella", "email": "donatellafelletti@gmail.com"},
    {"nome": "Scarso Riccardo", "email": "scarso.riccardo@gmail.com"},
    {"nome": "Fortin Michele", "email": "michel.fortin10@gmail.com"},
    {"nome": "Kiropratica - Ferraro Devid", "email": "djf@kiropraticaitalia.it"},
    {"nome": "Carrozzo Azzurra", "email": "azzurra.car@hotmail.it", "codice_fiscale": "CRRZRR92E66F152S"},
    {"nome": "Rau Valeria", "email": "alinamunte2000y@icloud.com"},
    {"nome": "Zugno Valter", "email": "valterzugno49@gmail.com", "codice_fiscale": "ZGNVTR49T20B345F"},
    {"nome": "Marangoni Francesco", "email": "francesco0marangoni@gmail.com"},
    {"nome": "Ruzza Giovanni", "email": "gio.ruzza1994@gmail.com"},
    {"nome": "Zaramella Sabrina", "email": "sabrinazaramella.mov@gmail.com", "codice_fiscale": "ZRMSRN69B56B546S"},
    {"nome": "Lo Presti Jessica", "email": "jessica.lopresti@hotmail.it"},
    {"nome": "Rossetto Daria", "email": "rossettodaria@gmail.com", "codice_fiscale": "RSSDRA88"},
    {"nome": "Pegoraro Giada", "email": "giada.peg.97@gmail.com"},
    {"nome": "Emigrato Roberto", "email": "emigratoroberto@gmail.com"},
    {"nome": "Avv. Stivan Nazareno", "email": "nazareno.stivanello@me.com"},
    {"nome": "Belotcaci Dumitru", "email": "dumitru.belotcaci@gmail.com"},
    {"nome": "Sfera Spa - Bisello Nicola", "email": "commerci.societasferaspa@pec.it", "ragione_sociale": "Sfera Spa", "tipo_cliente": "azienda"},
    {"nome": "Diaconu Darius", "email": "darius.diaconu@live.it"},
    {"nome": "Pontidoro Fabio", "email": "fabiopontidoro@hotmail.it"},
    {"nome": "Ing. Fischetti", "email": "m.fischetti.glf@gmail.com"},
    {"nome": "Barzon Edoardo", "email": "edo.barzon@libero.it"},
    {"nome": "Trosani Dario", "email": "bledartroshani@libero.it"},
    {"nome": "Fiorentini Annalisa", "email": "fiorelisa74@gmail.com"},
    {"nome": "Bassan Giorgia", "email": "giorgiabassan9@gmail.com"},
    {"nome": "Brun Carla Silvia", "email": "silvia.bruncardo@gmail.com"},
    {"nome": "Lucis Alessandro", "email": "alessandrolucis@libero.it"},
    {"nome": "Sabbadin Mariapia", "email": "marysun_28@yahoo.it"},
    {"nome": "Celeghin Andrea", "email": "celeghin.a.celeghin@pec.it"},
    {"nome": "Morello Demetrio", "email": "demetriomorello1998@libero.it"},
    {"nome": "Comm. Sin Igor", "email": "stecca.ennio@libero.it"},
    {"nome": "Grando Donatella", "email": "grando@libero.it"},
    {"nome": "Immobiliare Lincetto", "email": "antonellalli@gmail.com"},
    {"nome": "Zambonin Patrizia", "email": "pzambonin@interpolimeri.it"},
    {"nome": "Kazbek Khaizabekov", "email": "kazbek.khaizabekov@studenti.unipd.it"},
    {"nome": "Rampazzo Laura", "email": "laurarampazzo@hotmail.it"},
    {"nome": "Marangon Moreno", "email": "maranga857@gmail.com"},
    {"nome": "Puliafito Domenico", "email": "domenico3897@gmail.com"},
    {"nome": "Cantavalle Vittorio", "email": "cantavallevittorio@gmail.com"},
    {"nome": "Zanini Secondo", "email": "zanini.secondo@libero.it"},
    {"nome": "Corrado Giulia", "email": "gcorrado@luc.edu"},
    {"nome": "Bonini Valentino Horacio", "email": "valenbonini@gmail.com"},
    {"nome": "Mingati Giovanni", "email": "ing.mingati@gmail.com"},
    {"nome": "Stecca Ennio", "email": "stecca.ennio@libero.it"},
    {"nome": "Golin Rosa Maria", "email": "rosamariagolin@gmail.com"},
    {"nome": "Testolina Andrea", "email": "andreatestolina@icloud.com"},
    {"nome": "Costa Giuseppe", "email": "peycosta@libero.it", "codice_fiscale": "CSTGPP73S09G273J"},
    {"nome": "Seganfreddo Elena", "email": "elena.seganfreddo@libero.it"},
    {"nome": "Tagliabracci Lisa", "email": "lisatagliabracci@gmail.com", "codice_fiscale": "TGLLSI04H56G479K"},
    {"nome": "Ape Geom. Bonato Daniele", "email": "dbtecnicogeom@gmail.com"},
    {"nome": "Petre", "email": "petra2188@gmail.com"},
    {"nome": "Bizzotto Lisa", "email": "lisa.bizzotto.b@gmail.com"},
    {"nome": "Modesto Marco", "email": "marco@jasspro.it"},
    {"nome": "Da Rios Gianpaolo", "email": "giampaolodr9@gmail.com"},
    {"nome": "Edo Trasporti Srl", "email": "edotrasportisrl@yahoo.com", "ragione_sociale": "Edo Trasporti Srl", "tipo_cliente": "azienda"},
    {"nome": "Celot Noemi", "email": "noemicelot03@gmail.com", "codice_fiscale": "CLTNMO03T71C957P"},
    {"nome": "Cervone Tamara Emanuela", "email": "tamaracer.92@hotmail.it", "codice_fiscale": "CRVTMR92C48I158Y"},
    {"nome": "Immobiliare S.D'Acquisto - Miatto Nadia", "email": "miattonadia@gmail.com", "ragione_sociale": "Immobiliare S.D'Acquisto Srl", "tipo_cliente": "azienda"},
    {"nome": "Nord Est Buro - Pintonello Nicola", "email": "pintonello.n@gmail.com", "ragione_sociale": "Nord Est Buro Srl", "tipo_cliente": "azienda"},
    {"nome": "Tomasi Adriano", "email": "paolotta48@libero.it"},
    {"nome": "Zarpellon Silvia", "email": "zetatabacchi@arubapec.it"},
    {"nome": "Alberti Oreste", "email": "orestealberti71@gmail.com", "codice_fiscale": "LBRRST71P04G224J"},
    {"nome": "Baietta Riccardo", "email": "r.baietta@gmail.com", "codice_fiscale": "BTTRCR70L10G224N"},
    {"nome": "Calderone Jordan", "email": "jordan.calderone1995@gmail.com", "codice_fiscale": "CLDJDN95R25D969W"},
    {"nome": "Carraro Leopoldo", "email": "leopoldocarraro@virgilio.it", "codice_fiscale": "CRRLLD57E27E592X"},
    {"nome": "Mazzon Davide", "email": "davide.mazzon92@gmail.com", "codice_fiscale": "MZZDVD92M09B563P"},
    {"nome": "Tiraboschi Silvia", "email": "silviatiraboschi4@gmail.com", "codice_fiscale": "TRBSLV97S57B157D"},
    {"nome": "Puma Simone", "email": "simone.puma1994@gmail.com", "codice_fiscale": "PMUSMN94S05H163U"},
    {"nome": "Rusu Adi Gheorghita", "email": "bejanalexandra87@gmail.com", "codice_fiscale": "RSUDHR94D16Z129T"},
    {"nome": "Pristerà Simone", "email": "simonepristera@gmail.com"},
    {"nome": "Rosca Viorel", "email": "rosca1557@gmail.com"},
    {"nome": "Bertazzo Ivan", "email": "ivanbertazzo82@gmail.com"},
    {"nome": "Pal Francesco", "email": "francesco.pal54@gmail.com", "codice_fiscale": "PLAFNC03D27C743Y"},
    {"nome": "Bellot Romanet Federico", "email": "federico.bellot@studio-brc.it"},
    {"nome": "Palizzari Chiara", "email": "panizzari.chiara94@gmail.com"},
    {"nome": "Barcaro Denis", "email": "d.barcaro@casanogas.it"},
    {"nome": "Sellarini Fabio", "email": "f.sellarini@coricelli.com", "codice_fiscale": "SLLFBA75D20I921R"},
    {"nome": "Palango Gloria", "email": "palangogloria@gmail.com"},
    {"nome": "Girardello Stefano", "email": "frigosamat@hotmail.com", "codice_fiscale": "GRRSFN67R23L840C"},
    {"nome": "Marampon Masha", "email": "vsserviziitalia@gmail.com", "codice_fiscale": "MRMMSH92L25G224S"},
    {"nome": "Ousmanou Issa", "email": "issaousmanou435@gmail.com"},
    {"nome": "Bertato Katia", "email": "katiabertato74@gmail.com", "codice_fiscale": "BRTKTA74S69B563M"},
    {"nome": "Lunardi Annamaria", "email": "lunardi.anna54@gmail.com", "codice_fiscale": "LNRNMR54T51Z600U"},
    {"nome": "Adami Claudia", "email": "dmacld66p44l949t@gmail.com"},
    {"nome": "Moressa Silvano", "email": "lovisonlella@gmail.com", "codice_fiscale": "MRSSVN59H15I275S"},
    {"nome": "Odeyemi Alberto", "email": "albertoodeyemi@hotmail.com"},
    {"nome": "Micheletto Paolo", "email": "padova@gruppobm.it"},
    {"nome": "Corso Maria Cristina", "email": "corso.mariacristina7@libero.it", "codice_fiscale": "CRSMCR73E61D423U"},
    {"nome": "Zilio Isabella", "email": "isabellazilio36@gmail.com", "codice_fiscale": "ZLISLL73C43E592X"},
    {"nome": "Tecnofur Snc", "email": "info@tecnofur.com", "ragione_sociale": "Tecnofur Snc", "tipo_cliente": "azienda"},
    {"nome": "Zamberlan Massimo", "email": "maxzambo1@gmail.com"},
    {"nome": "Engyn Soft - Silvia", "email": "s.galtarossa@enginsoft.com"},
    {"nome": "Palazzo Giovanni", "email": "giovannipalazzomail@gmail.com", "codice_fiscale": "PLZGNN81R04L738H"},
    {"nome": "Busato Giovanni", "email": "busatogiovanni@gmail.com"},
    {"nome": "Giacomini Claudia", "email": "giacominiclaudia@gmail.com"},
    {"nome": "Lbrus & Blanc - Stecca Michele", "email": "thuono@gmail.com", "ragione_sociale": "Lbrus & Blanc Consulting", "tipo_cliente": "azienda"},
    {"nome": "Veronica", "email": "ficumora@hotmail.it"},
    {"nome": "Riciardello Nicolò", "email": "spinemedical@gmail.com"},
    {"nome": "Milani Alberto", "email": "alby.milani@gmail.com"},
    {"nome": "Sabbadin Mariapia", "email": "marysun_28@yahoo.it"},
    {"nome": "Pontidoro Fabio", "email": "fabiopontidoro@hotmail.it"},
    {"nome": "Salvan Andrea", "email": "salefra4@gmail.com"},
    {"nome": "Rabito Lorena", "email": "lorenarabito@gmail.com"},
    {"nome": "Bertinato Miriam", "email": "bertinatomiriam@gmail.com"},
]

def main():
    # Deduplicate by email
    seen = set()
    unique = []
    for c in CONTACTS:
        email = c['email'].lower().strip()
        if email not in seen:
            seen.add(email)
            c['email'] = email
            c['fonte'] = 'import_csv'
            if 'tipo_cliente' not in c:
                c['tipo_cliente'] = 'privato'
            unique.append(c)

    print(f"Contatti unici da caricare: {len(unique)}")

    # Upload in batches
    BATCH = 50
    ok = 0
    fail = 0

    for i in range(0, len(unique), BATCH):
        batch = unique[i:i+BATCH]
        r = requests.post(
            f"{SUPABASE_URL}/rest/v1/clienti",
            headers=HEADERS,
            json=batch
        )
        if r.status_code in (200, 201):
            ok += len(batch)
            print(f"  Batch {i//BATCH+1}: {len(batch)} caricati OK")
        else:
            print(f"  Batch {i//BATCH+1}: ERRORE {r.status_code} - {r.text[:200]}")
            # Try one by one
            for rec in batch:
                r2 = requests.post(
                    f"{SUPABASE_URL}/rest/v1/clienti",
                    headers=HEADERS,
                    json=rec
                )
                if r2.status_code in (200, 201):
                    ok += 1
                else:
                    fail += 1
                    print(f"    SKIP {rec['email']}: {r2.text[:80]}")
        time.sleep(0.3)

    print(f"\nRISULTATO: {ok} caricati, {fail} errori su {len(unique)} totali")

if __name__ == '__main__':
    main()
